[package]
name = "pop-launcher-bin"
version = "1.2.1"
edition = "2018"
license = "GPL-3.0-only"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pop-launcher-toolkit = { path = "../toolkit" }
tracing = "0.1.32"
tracing-subscriber = { version = "0.3.9", default-features = false, features = ["std", "fmt", "env-filter"] }
dirs = "4.0.0"
mimalloc = "0.1.28"

[dependencies.tokio]
version = "1.17.0"
features = ["rt"]
